app.bootstrap-servers=localhost:9092
app.topic.input=input-event
app.topic.cache-log=cache-log-event
app.topic.processed=processed-event
app.topic.partitions=6

app.batch.max-records=100
app.batch.max-wait-ms=1000
app.poll-timeout-ms=200

app.cache.heap-entries=10000

app.producer.client-id=tx-cache-producer
app.producer.transaction-id-prefix=tx-cache-

app.shard-index=0
app.shard-count=1